# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: St Margarets Community Website
email: editor@stmgrts.org.uk
description: > # this means to ignore newlines until "baseurl:"
  St Margarets Community Website provides residents and visitors great information about local news, events and resources.  St Margarets is in Greater London and located between Twickenham and Richmond.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://stmargarets.london" # the base hostname & protocol for your site
twitter_username: stmgrts
github_username:  pmahnke
incremental: true
timezone: Etc/GMT

exclude:
    - node_modules

# gems
plugins:
  - jekyll-archives
#  - jekyll-textile-converter

# Build settings
markdown: kramdown
# textile_ext: "textile,txtl,tl"
sass:
    style: compressed
    sass_dir: _sass

jekyll-archives:
  enabled:
    - year
    - month
    - categories
  layouts:
    year: year-archive
    month: month-archive
    category: category-archive
  permalinks:
    year: '/archives/:year/'
    month: '/archives/:year/:month/'
    category: '/archives/:name/'
